version: '3.8'

services:
  db:
    container_name: food_explorer_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
      - PG_HOST=localhost
      - PG_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: